---
- name: Update Ubuntu and Amazon Linux servers
  hosts: all
  become: yes

  tasks:
    - name: Update Ubuntu servers
      apt:
        update_cache: yes
        upgrade: dist
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update Amazon Linux servers
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Amazon"
